// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Xunit;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;
using Xunit.Abstractions;
using System;
using System.Collections.Generic;

namespace CppWrapperExample.Tests
{
    public class FunctionTests
    {
        private readonly ITestOutputHelper output;

        public FunctionTests(ITestOutputHelper output)
        {
            this.output = output;
        }

        [Fact]
        public void CallsWrapperMethodSuccessfully()
        {
            CppWrapperExample.Execute(new Dictionary<string, Elements.Model>(), new CppWrapperExampleInputs(1, 1, null, null, null, null, null, null));
        }
    }
}